java_library(
    name = 'common-kafka-configuration',
    srcs = glob(['*.java']),
    deps = [
        '//lib/kafka:kafka-clients',
        '//lib/spring:spring-boot',
        '//lib/spring:spring-context',
    ],
    visibility = [
        'PUBLIC',
    ]
)