java_library(
    name = 'migrator-api',
    srcs = glob(['*.java']),
    deps = [
        '//lib/mongo:mongodb-driver'
    ],
    visibility = [
        '//src/uk/gov/dwp/migrator/...',
        '//test/uk/gov/dwp/migrator/...',
    ]
)