java_test(
    name = 'test',
    srcs = glob(['*.java']),
    resources = [
        'resources/sampleKafkaMessages.json',
    ],
    resources_root = 'resources',
    deps = [
        '//lib:commons-io',
        '//lib/jackson:jackson-databind',
        '//lib/mongo:mongodb-driver',
        '//lib/spring:spring-context',
        '//lib/test:common',
        '//lib/test:json-assert',
        '//src/uk/gov/dwp/common/jackson:common-jackson',
        '//src/uk/gov/dwp/common/jackson/spring:common-jackson-spring',
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
    ],
)