java_library(
    name = 'migration-mongo-configuration',
    srcs = glob(['*.java']),
    exported_deps = [
        '//src/uk/gov/dwp/migration/mongo:migration-mongo',
    ],
    deps = [
        '//lib/mongo:mongodb-driver',
        '//lib/spring:spring-boot',
        '//lib/spring:spring-context',
        '//src/uk/gov/dwp/common/id:common-id',
        '//src/uk/gov/dwp/common/kafka/configuration:common-kafka-configuration',
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
        '//src/uk/gov/dwp/common/kafka/mongo/producer:common-kafka-mongo-producer',
        '//src/uk/gov/dwp/common/kafka/mongo/producer/configuration:common-kafka-mongo-producer-configuration',
        '//src/uk/gov/dwp/common/mongo:common-mongo',
        '//src/uk/gov/dwp/migration/mongo/api:migration-mongo-api',
        '//src/uk/gov/dwp/migration/mongo/kafka/api:migration-mongo-kafka-api',
        '//src/uk/gov/dwp/migration/mongo/kafka/consumer:migration-mongo-kafka-consumer',
    ],
    visibility = [
        '//src/uk/gov/dwp/migration/mongo/kafka/consumer/configuration:migration-mongo-kafka-consumer-configuration',
        '//src/uk/gov/dwp/personal/details/server/migration/...',
    ],
)