java_library(
    name = 'common-mongo-test-support',
    srcs = glob(['*.java']),
    deps = [
        '//lib/mongo:mongodb-driver',
        '//lib/slf4j:slf4j-api',
#         '//lib/spring:spring-beans',
#         '//lib/spring:spring-boot-autoconfigure',
#         '//lib/spring:spring-boot-test',
#         '//lib/spring:spring-context',
#         '//lib/spring:spring-test',
        '//lib/test:common',
    ],
    visibility = [
        'PUBLIC',
    ]
)
