java_library(
    name = 'personal-details-client',
    srcs = glob(['*.java']),
    deps = [
        '//src/uk/gov/dwp/common/id:common-id',
        '//src/uk/gov/dwp/personal/details/api:personal-details-api',
        '//lib:commons-lang3',
        '//lib:javafaker',
        '//lib/slf4j:slf4j-api',
    ],
    visibility = [
        'PUBLIC'
    ]
)