java_library(
    name = 'migration-mongo-api',
    srcs = glob(['*.java']),
    deps = [
        '//lib/mongo:mongodb-driver'
    ],
    visibility = [
        '//src/uk/gov/dwp/migration/...',
        '//test/uk/gov/dwp/migration/...',
    ]
)