java_library(
    name = 'migration-mongo-api',
    srcs = glob(['*.java']),
    deps = [
        '//lib/mongo:mongodb-driver'
    ],
    visibility = [
        '//src/uk/gov/dwp/migration/...',
        '//src/uk/gov/dwp/personal/details/server/migration/...',
        '//src/uk/gov/dwp/personal/details/server:personal-details-server',
        '//test/uk/gov/dwp/migration/...',
        '//test/uk/gov/dwp/personal/details/server/migration:test',
        '//test/uk/gov/dwp/personal/details/server/migration/acceptance:test',
    ]
)