java_library(
    name = 'personal-details-resource',
    srcs = glob(['*.java']),
    deps = [
        '//lib/javax:javax-ws-rs-api',
        '//src/uk/gov/dwp/personal/details/client:personal-details-client',
        '//src/uk/gov/dwp/personal/details/server/dao:personal-details-dao',
    ],
    visibility = [
        '//src/uk/gov/dwp/personal/details/server/resource/configuration:personal-details-resource-configuration',
        '//src/uk/gov/dwp/personal/details/server:personal-details-docker',
        '//src/uk/gov/dwp/personal/details/server:personal-details-server',
        '//test/uk/gov/dwp/personal/details/server/resource:test',
    ],
)