include_defs('//src/uk/gov/dwp/buck/docker.def')

PERSONAL_DETAILS_SERVER_LIBS = [
    '//lib:snakeyaml',
    '//lib/apache-cxf:cxf-rt-transports-http-jetty',
    '//lib/jackson:jackson-jaxrs-json-provider',
    '//lib/javax:javax-annotation-api',
    '//lib/javax:javax-servlet-api',
    '//lib/javax:javax-ws-rs-api',
    '//lib/jetty:jetty-server',
    '//lib/logback:logback-classic',
    '//lib/logback:logback-core',
    '//lib/slf4j:jcl-over-slf4j',
    '//lib/slf4j:jul-to-slf4j',
    '//lib/slf4j:log4j-over-slf4j',
    '//lib/slf4j:slf4j-api',
    '//lib/spring:spring-boot-autoconfigure',
    '//lib/spring:spring-boot-with-dependencies',
    '//lib/spring:spring-web',
    '//src/uk/gov/dwp/common/cxf/configuration:common-cxf-configuration',
    '//src/uk/gov/dwp/common/cxf/server:common-cxf-server',
    '//src/uk/gov/dwp/common/health:common-health',
    '//src/uk/gov/dwp/common/jackson:common-jackson',
    '//src/uk/gov/dwp/common/jackson/spring:common-jackson-spring',
    '//src/uk/gov/dwp/common/kafka/configuration:common-kafka-configuration',
    '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
    '//src/uk/gov/dwp/common/kafka/mongo/producer:common-kafka-mongo-producer',
    '//src/uk/gov/dwp/common/kafka/mongo/producer/configuration:common-kafka-mongo-producer-configuration',
    '//src/uk/gov/dwp/common/mongo:common-mongo',
    '//src/uk/gov/dwp/personal/details/client:personal-details-client',
    '//src/uk/gov/dwp/personal/details/server/dao:personal-details-dao',
    '//src/uk/gov/dwp/personal/details/server/dao/mongo:personal-details-dao-mongo',
    '//src/uk/gov/dwp/personal/details/server/resource:personal-details-resource',
    '//src/uk/gov/dwp/personal/details/server/resource/configuration:personal-details-resource-configuration',
]

java_library(
    name = 'personal-details-server',
    srcs = glob(['*.java']),
    resources = [
        'resources/application.yml',
        'resources/logback.xml',
    ],
    resources_root = 'resources',
    deps = PERSONAL_DETAILS_SERVER_LIBS,
    visibility = [
        'PUBLIC'
    ]
)

docker_build(
    name = 'docker-build',
    app_home = '/srv/app',
    cmd = 'CMD java -cp "/srv/app/lib/*" uk.gov.dwp.personal.details.server.PersonalDetailsServer',
    lib = [
        '$(classpath :personal-details-server)',
    ],
    tag = 'personal-details-server:1.0',
)