java_library(
    name = 'common-kafka-mongo-producer-configuration',
    srcs = glob(['*.java']),
    deps = [
        '//lib/kafka:kafka-clients-with-dependencies',
        '//lib/slf4j:slf4j-api',
        '//lib/spring:spring-boot',
        '//lib/spring:spring-context',
        '//src/uk/gov/dwp/common/jackson/spring:common-jackson-spring',
        '//src/uk/gov/dwp/common/kafka/configuration:common-kafka-configuration',
        '//src/uk/gov/dwp/common/kafka/mongo/producer:common-kafka-mongo-producer',
    ],
    visibility = [
        'PUBLIC',
    ]
)