java_library(
    name = 'common-cxf-server',
    srcs = glob(['*.java']),
    exported_deps = [
        '//src/uk/gov/dwp/common/cxf/configuration:common-cxf-configuration',
        '//lib/apache-cxf:cxf-rt-transports-http-jetty',
        '//lib/javax:javax-servlet-api',
        '//lib/spring:spring-boot',
        '//lib/spring:spring-boot-autoconfigure',
        '//lib/spring:spring-context',
        '//lib/spring:spring-core',
    ],
    visibility = [
        'PUBLIC'
    ],
)
