java_library(
    name = 'personal-details-dao-mongo',
    srcs = glob(['**/*.java']),
    deps = [
        '//lib/jackson:jackson-databind',
        '//lib/kafka:kafka-clients-with-dependencies',
        '//lib/mongo:mongodb-driver',
        '//lib/slf4j:slf4j-api',
        '//lib/spring:spring-boot',
        '//lib/spring:spring-context',
        '//src/uk/gov/dwp/common/jackson/spring:common-jackson-spring',
        '//src/uk/gov/dwp/common/kafka/configuration:common-kafka-configuration',
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
        '//src/uk/gov/dwp/common/kafka/mongo/producer:common-kafka-mongo-producer',
        '//src/uk/gov/dwp/common/kafka/mongo/producer/configuration:common-kafka-mongo-producer-configuration',
        '//src/uk/gov/dwp/common/mongo:common-mongo',
        '//src/uk/gov/dwp/common/mongo/codec:common-mongo-codec',
        '//src/uk/gov/dwp/personal/details/client:personal-details-client',
        '//src/uk/gov/dwp/personal/details/server/dao:personal-details-dao',
        '//src/uk/gov/dwp/personal/details/server/model:personal-details-model',
    ],
    visibility = [
        'PUBLIC'
    ]
)

export_file(
    name = 'mongo-personal-details-roles.sh',
    src  = 'mongo-personal-details-roles.sh',
)

export_file(
    name = 'mongo-personal-details-users.sh',
    src  = 'mongo-personal-details-users.sh',
)

genrule(
    name = 'create-users-and-roles',
    cmd = '$(location :mongo-personal-details-roles.sh) > $OUT && $(location :mongo-personal-details-users.sh) >> $OUT',
    out = 'create-users-and-roles.log'
)
