java_library(
    name = 'personal-details-resource-configuration',
    srcs = glob(['*.java']),
    deps = [
        '//lib/javax:javax-ws-rs-api',
        '//lib/spring:spring-boot',
        '//lib/spring:spring-context',
        '//src/uk/gov/dwp/common/cxf/configuration:common-cxf-configuration',
        '//src/uk/gov/dwp/personal/details/client:personal-details-client',
        '//src/uk/gov/dwp/personal/details/server/dao:personal-details-dao',
        '//src/uk/gov/dwp/personal/details/server/dao/mongo:personal-details-dao-mongo',
        '//src/uk/gov/dwp/personal/details/server/migration:personal-details-server-migration',
        '//src/uk/gov/dwp/personal/details/server/resource:personal-details-resource',
    ],
    visibility = [
        '//src/uk/gov/dwp/personal/details/server:personal-details-docker',
        '//src/uk/gov/dwp/personal/details/server:personal-details-server',
    ],
)