java_library(
    name = 'dao-mongo-test-support',
    srcs = glob(['*.java']),
    resources = [
        'mongo-dao-test.properties'
    ],
    resources_root = '.',
    deps = [
        '//src/uk/gov/dwp/personal/details/server/dao/mongo:personal-details-dao-mongo',
        '//lib/mongo:mongodb-driver',
        '//lib/slf4j:slf4j-api',
        '//lib/spring:spring-beans',
        '//lib/spring:spring-boot-autoconfigure',
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-context',
        '//lib/spring:spring-test',
        '//lib/test:hamcrest-core',
        '//lib/test:junit',
    ],
    visibility = [
        'PUBLIC',
    ]
)
