java_library(
    name = 'dao-mongo-test-support',
    srcs = glob(['*.java']),
    resources = [
        'resources/mongo-dao-test.properties'
    ],
    resources_root = 'resources',
    deps = [
        '//lib/mongo:mongodb-driver',
        '//lib/slf4j:slf4j-api',
        '//lib/spring:spring-beans',
        '//lib/spring:spring-boot-autoconfigure',
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-context',
        '//lib/spring:spring-test',
        '//lib/test:common',
        '//src/uk/gov/dwp/common/kafka/mongo/producer:common-kafka-mongo-producer',
        '//src/uk/gov/dwp/common/mongo/test/support:common-mongo-test-support',
        '//src/uk/gov/dwp/personal/details/server/dao/mongo:personal-details-dao-mongo',
    ],
    visibility = [
        'PUBLIC',
    ]
)
