java_library(
    name = 'migrator-mongo',
    srcs = glob(['*.java']),
    deps = [
        '//lib/mongo:mongodb-driver',
        '//lib/slf4j:slf4j-api',
        '//src/uk/gov/dwp/migrator/api:migrator-api',
        '//src/uk/gov/dwp/migrator/notification:migrator-notification',
    ],
    visibility = [
        '//test/uk/gov/dwp/migrator/...',
    ]
)