java_library(
    name = 'common-health',
    srcs = glob(['*.java']),
    deps = [
        '//lib/javax:javax-servlet-api',
    ],
    visibility = [
        '//src/uk/gov/dwp/personal/details/server:personal-details-server',
        '//src/uk/gov/dwp/migration/server:migration-server',
        '//test/uk/gov/dwp/common/health:test',
    ]
)

