java_library(
    name = 'common-kafka-mongo-api-test-support',
    srcs = glob(['*.java']),
    deps = [
        '//lib:commons-lang3',
        '//lib/jackson:jackson-annotations',
        '//lib/jackson:jackson-databind',
        '//lib/mongo:bson',
        '//lib/slf4j:slf4j-api',
        '//lib/test:hamcrest-core',
        '//src/uk/gov/dwp/common/id:common-id',
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
    ],
    visibility = [
        '//test/...',
    ]
)