java_test(
    name = 'test',
    srcs = glob(['*.java']),
    deps = [
        '//lib/mongo:mongodb-driver',
        '//lib/test:common',
        '//src/uk/gov/dwp/migrator/api:migrator-api',
        '//src/uk/gov/dwp/migrator/mongo:migrator-mongo',
    ],
)