java_library(
    name = 'common-kafka-mongo-api',
    srcs = glob(['*.java']),
    deps = [
        '//lib:commons-lang3',
        '//lib/jackson:jackson-annotations',
        '//lib/jackson:jackson-databind',
        '//lib/slf4j:slf4j-api',
        '//src/uk/gov/dwp/common/id:common-id',
    ],
    visibility = [
        'PUBLIC',
    ]
)