java_library(
    name = 'migration-kafka',
    srcs = glob(['*.java']),
    deps = [
        '//lib/kafka:kafka-clients-with-dependencies',
        '//lib/mongo:mongodb-driver',
        '//lib/slf4j:slf4j-api',
        '//src/uk/gov/dwp/migration/api:migration-api',
    ],
    visibility = [
        'PUBLIC',
    ],
)