java_test(
    name = 'test',
    srcs = glob(['*.java']),
    deps = [
        '//lib/mongo:mongodb-driver',
        '//lib/test:common',
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
        '//src/uk/gov/dwp/common/kafka/mongo/api/test/support:common-kafka-mongo-api-test-support',
        '//src/uk/gov/dwp/common/kafka/mongo/producer:common-kafka-mongo-producer',
        '//src/uk/gov/dwp/common/mongo/test/support:common-mongo-test-support',
        '//src/uk/gov/dwp/migration/mongo:migration-mongo',
        '//src/uk/gov/dwp/migration/mongo/api:migration-mongo-api',
        '//src/uk/gov/dwp/migration/mongo/kafka/api:migration-mongo-kafka-api',
    ],
)