java_test(
    name = 'test',
    srcs = glob(['*.java']),
    deps = [
        '//lib/mongo:mongodb-driver',
        '//lib/test:common',
        '//src/uk/gov/dwp/migration/api:migration-api',
        '//src/uk/gov/dwp/migration/mongo:migration-mongo',
    ],
)