java_test(
    name = 'test',
    srcs = glob(['**/*.java']),
    resources = [
        'spring/resources/mongo-dao-defaults.yml',
        'spring/resources/mongo-dao-multiple-servers-and-auth.yml',
    ],
    resources_root = 'spring/resources',
    deps = [
        '//lib:commons-logging',
        '//lib:snakeyaml',
        '//lib/mongo:mongodb-driver',
        '//lib/spring:spring-boot-test',
        '//lib/spring:spring-boot-with-dependencies',
        '//lib/spring:spring-test',
        '//lib/test:common',
        '//src/uk/gov/dwp/common/mongo:common-mongo',
        '//src/uk/gov/dwp/personal/details/api:personal-details-api',
        '//src/uk/gov/dwp/personal/details/api/test/support:personal-details-api-test-support',
        '//src/uk/gov/dwp/personal/details/server/dao:personal-details-dao',
        '//src/uk/gov/dwp/personal/details/server/dao/mongo:personal-details-dao-mongo',
        '//test/uk/gov/dwp/personal/details/server/dao/support:dao-mongo-test-support',
    ]
)