java_library(
    name = 'migration-mongo',
    srcs = glob(['*.java']),
    deps = [
        '//lib/mongo:mongodb-driver',
        '//lib/slf4j:slf4j-api',
        '//src/uk/gov/dwp/migration/api:migration-api',
        '//src/uk/gov/dwp/migration/notification:migration-notification',
    ],
    visibility = [
        '//test/uk/gov/dwp/migration/...',
    ]
)