java_library(
    name = 'migration-mongo',
    srcs = glob(['*.java']),
    deps = [
        '//lib/jackson:jackson-core',
        '//lib/mongo:mongodb-driver',
        '//lib/slf4j:slf4j-api',
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
        '//src/uk/gov/dwp/common/kafka/mongo/producer:common-kafka-mongo-producer',
        '//src/uk/gov/dwp/migration/mongo/api:migration-mongo-api',
        '//src/uk/gov/dwp/migration/mongo/kafka/api:migration-mongo-kafka-api',
    ],
    visibility = [
        '//src/uk/gov/dwp/migration/mongo/configuration:migration-mongo-configuration',
        '//src/uk/gov/dwp/personal/details/server/migration/...',
        '//test/uk/gov/dwp/migration/...',
    ]
)