java_library(
    name = 'migration-kafka-consumer-configuration',
    srcs = glob(['*.java']),
    deps = [
        '//lib:commons-lang3',
        '//lib/jackson:jackson-annotations',
        '//lib/jackson:jackson-core',
        '//lib/jackson:jackson-databind',
        '//lib/kafka:kafka-clients-with-dependencies',
        '//lib/slf4j:slf4j-api',
        '//lib/spring:spring-boot',
        '//lib/spring:spring-context',
        '//src/uk/gov/dwp/common/id:common-id',
        '//src/uk/gov/dwp/common/jackson/spring:common-jackson-spring',
        '//src/uk/gov/dwp/common/kafka/configuration:common-kafka-configuration',
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
        '//src/uk/gov/dwp/migration/kafka/api:migration-kafka-api',
        '//src/uk/gov/dwp/migration/kafka/consumer:migration-kafka-consumer',
        '//src/uk/gov/dwp/migration/mongo/configuration:migration-mongo-configuration',
    ],
    visibility = [
        'PUBLIC',
    ]
)