java_test(
    name = 'personal-details-client',
    srcs = glob(['**/*.java']),
    deps = [
        '//lib/slf4j:slf4j-api',
        '//lib/test:common',
        '//src/uk/gov/dwp/personal/details/api:personal-details-api',
        '//src/uk/gov/dwp/personal/details/client:personal-details-client',
    ],
)