java_test(
	name = 'test',
	srcs = glob(['*.java','v2/*.java']),
	deps = [
		'//lib/javax:javax-ws-rs-api',
        '//lib/test:common',
        '//src/uk/gov/dwp/personal/details/client:personal-details-client',
        '//src/uk/gov/dwp/personal/details/server/dao:personal-details-dao',
        '//src/uk/gov/dwp/personal/details/server/model:personal-details-model',
        '//src/uk/gov/dwp/personal/details/server/resource:personal-details-resource',
	],
)
