java_library(
    name = 'migration-resource',
    srcs = glob(['*.java']),
    deps = [
        '//lib/javax:javax-ws-rs-api',
    ],
    visibility = [
        '//src/uk/gov/dwp/migration/server/resource/configuration:migration-resource-configuration',
        '//src/uk/gov/dwp/migration/server:migration-server',
    ],
)