java_library(
    name = 'personal-details-client-test-support',
    srcs = glob(['*.java']),
    deps = [
        '//lib/test:hamcrest-core',
        '//lib/test:hamcrest-library',
        '//src/uk/gov/dwp/personal/details/server/model:personal-details-model',
    ],
    visibility = [
#        '//test/uk/gov/dwp/personal/details/server/dao/mongo:test',
	'//test/...',
    ],
)
