java_library(
    name = 'personal-details-dao',
    srcs = glob(['*.java']),
    deps = [
        '//src/uk/gov/dwp/common/id:common-id',
        '//src/uk/gov/dwp/personal/details/api:personal-details-api',
        '//lib/javax:javax-ws-rs-api',
    ],
    visibility = [
        'PUBLIC'
    ]
)