java_library(
    name = 'migration-mongo-kafka-api',
    srcs = glob(['*.java']),
    deps = [
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
    ],
    visibility = [
        'PUBLIC',
    ]
)