java_test(
    name = 'test',
    srcs = glob(['*.java']),
    deps = [
        '//lib/jackson:jackson-core',
        '//lib/kafka:kafka-clients-with-dependencies',
        '//lib/mongo:mongodb-driver',
        '//lib/test:common',
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
        '//src/uk/gov/dwp/common/kafka/mongo/producer:common-kafka-mongo-producer',
        '//src/uk/gov/dwp/migration/kafka/api:migration-kafka-api',
    ],
)