java_test(
    name = 'test',
    srcs = glob(['*.java']),
    deps = [
        '//lib/jackson:jackson-core',
        '//lib/jackson:jackson-databind',
        '//lib/kafka:kafka-clients-with-dependencies',
        '//lib/test:common',
        '//src/uk/gov/dwp/common/kafka/mongo/api:common-kafka-mongo-api',
        '//src/uk/gov/dwp/migration/mongo/kafka/api:migration-mongo-kafka-api',
        '//src/uk/gov/dwp/migration/mongo/kafka/consumer:migration-mongo-kafka-consumer',
    ],
)